### ISSUE TITLE
Error while using `=` character inside string value

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [alyu/configparser#5]
I am getting string value from my config file like that:
```
section, err := f.config.Section("mytin-config")
// error hanling
apiURL := section.ValueOf("APIUrl")
```
If value of api url  was simple `my.host.lan/anypath` it's working, but when I pul `my.host.lan/anypath?filter1=test` it returns nothing

**Comment by alyu** [comment]
Added tests and those passes now.
